name: Crash Report
description: File a crash report
title: "[Crash]: "
labels: [ Crash ]
body:
  - type: markdown
    attributes:
      value: |
        **Prior to filling out this crash report, please make sure of the following:**
        - You tried on the latest version of the pack.
        - You don't have any other mods installed.
  - type: dropdown
    id: fixes
    attributes:
      label: Possible Fixes
      description: Have you tried the above mentioned points?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input
    id: pack-version
    attributes:
      label: Modpack Version
      description: What version of the pack are you using?
      placeholder: Pack version
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Please give a thorough explanation of what happened. Attach/Link relevant images/files in relation to the issue!
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: crash-log
    attributes:
      label: Crash Log
      description: Please upload your crash log to  https://gist.github.com/ and leave the link here. Located in `/<instance name>/crash-reports/`
      placeholder: https://gist.github.com/
    validations:
      required: true
  - type: input
    id: latest-log
    attributes:
      label: Latest.Log 
      description: Please upload your latest.log to  https://gist.github.com/ and leave the link here. Note this file is different to a crash report. Located in `/<instance name>/logs/`.
      placeholder: https://gist.github.com/
    validations:
      required: false
