ServerEvents.recipes(event => {
    event.recipes.gtceu.chemical_bath('kubejs:inert_star')
        .itemInputs('minecraft:wither_skeleton_skull')
        .inputFluids(Fluid.of('gtceu:polyethylene', 1000))
        .itemOutputs('kubejs:inert_nether_star')
        .duration(10)
        .EUt(IV)
    
    event.recipes.gtceu.mixer('kubejs:inert_fluid')
        .itemInputs('kubejs:inert_nether_star')
        .inputFluids(Fluid.of('gtceu:aqua_regia', 2000))
        .outputFluids(Fluid.of('gtceu:inert_nether_essence', 2304))
        .duration(12)
        .EUt(IV)
    
    event.recipes.gtceu.autoclave('kubejs:autoclave/nether_star')
        .itemInputs('gtceu:polyethylene_dust')
        .inputFluids(Fluid.of('gtceu:inert_nether_essence', 144))
        .itemOutputs('minecraft:nether_star')
        .duration(6)
        .EUt(EV)

    event.recipes.gtceu.arc_furnace('nan/its_a_joke')
        .itemInputs(Item.of('productivebees:configurable_honeycomb', '{EntityTag:{type:"productivebees:neutronium"}}').strongNBT())
        .inputFluids(Fluid.of('gtceu:oxygen_plasma', 100))
        .chancedOutput('2x gtceu:neutronium_nugget', 20, 5)
        .chancedOutput('gtceu:neutronium_nugget', 5, 5)
        .chancedOutput('gtceu:neutronium_nugget', 5, 5)
        .chancedOutput('gtceu:neutronium_nugget', 5, 5)
        .duration(25600)
        .EUt(ULV)
})