
ServerEvents.recipes(event => {
    event.recipes.gtceu.micro_universe_collector('naquadah_ore')
        .itemInputs('16x kubejs:micro_universe_catalyst', '1024x minecraft:end_stone')
        .circuit(1)
        .inputFluids(Fluid.of('gtceu:end_air', 1000000), Fluid.of('gtceu:nether_star', 144 * 64))
        .itemOutputs('128x gtceu:endstone_naquadah_ore', '128x gtceu:endstone_trinium_ore', '128x gtceu:endstone_plutonium_ore', '256x gtceu:endstone_tungstate_ore')
        .outputFluids(Fluid.of('gtceu:liquid_end_air', 64000), Fluid.of('gtceu:tritium', 8000))
        .duration(18000).EUt(UHV * 32)

    event.recipes.gtceu.micro_universe_collector('copper_ore')
        .itemInputs('16x kubejs:micro_universe_catalyst', '1024x minecraft:stone')
        .circuit(2)
        .inputFluids(Fluid.of('gtceu:air', 1000000), Fluid.of('gtceu:nether_star', 144 * 16))
        .itemOutputs('320x gtceu:copper_ore', '256x gtceu:tin_ore', '128x gtceu:iron_ore', '32x alltheores:allthemodium_ore')
        .duration(12000).EUt(UHV * 4)

    event.recipes.gtceu.micro_universe_collector('sulfur_ore')
        .itemInputs('16x kubejs:micro_universe_catalyst', '1024x minecraft:netherrack')
        .circuit(3)
        .inputFluids(Fluid.of('gtceu:nether_air', 1000000), Fluid.of('gtceu:nether_star', 144 * 16))
        .itemOutputs('320x gtceu:nether_sulfur_ore', '256x gtceu:nether_tetrahedrite_ore', '128x gtceu:nether_sphalerite_ore')
        .duration(12000).EUt(UHV * 4)

    event.recipes.gtceu.micro_universe_reactor('uhv_power')
        .itemInputs('16x kubejs:micro_universe_catalyst', '256x gtceu:tritium_ingot', '128x gtceu:neutronium_ingot')
        .circuit(1)
        .inputFluids(Fluid.of('gtceu:nether_star', 144 * 16))
        .duration(6000).EUt(-(UHV * 16))

    event.recipes.gtceu.micro_universe_reactor('uev_power')
        .itemInputs('16x kubejs:micro_universe_catalyst', '256x gtceu:tritium_ingot', '128x gtceu:neutronium_ingot', '1x #forge:batteries/uhv')
        .circuit(2)
        .inputFluids(Fluid.of('gtceu:nether_star', 144 * 16))
        .duration(6000).EUt(-(UEV * 8))
})